import { Question } from './types';

export const QUESTIONS_P1: Question[] = [
  {
    id: 0,
    letter: 'A',
    prefixType: 'Con la',
    verb: 'amar (սիրել)',
    tense: 'Futuro Simple',
    pronoun: 'yo',
    definition: 'Futuro simple de indicativo del verbo AMAR para la primera persona del singular (yo).',
    translation: 'AMAR (սիրել - տածել ուժեղ սեր կամ համակրանք) բայի Futuro Simple-ը եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'amaré',
    explanation: 'El futuro simple de los verbos regulares en -ar se forma agregando las terminaciones correspondientes (-é, -ás, -á, -emos, -éis, -án) al infinitivo completo del verbo.'
  },
  {
    id: 1,
    letter: 'B',
    prefixType: 'Con la',
    verb: 'beber (խմել)',
    tense: 'Futuro Perfecto',
    pronoun: 'tú',
    definition: 'Futuro perfecto de indicativo del verbo BEBER para la segunda persona del singular (tú).',
    translation: 'BEBER (խմել - հեղուկ կլանել, ծարավը հագեցնել) բայի Futuro Perfecto-ն եզակի երկրորդ դեմքի համար (tú - դու)։',
    answer: 'habrás bebido',
    explanation: 'El futuro perfecto (futuro compuesto) se construye con el futuro simple del verbo auxiliar "haber" (habrás) más el participio del verbo principal "beber" (bebido).'
  },
  {
    id: 2,
    letter: 'C',
    prefixType: 'Con la',
    verb: 'cantar (երգել)',
    tense: 'Futuro Simple',
    pronoun: 'él',
    definition: 'Futuro simple de indicativo del verbo CANTAR para la tercera persona del singular (él/ella).',
    translation: 'CANTAR (երգել - ձայնով երաժշտական հնչյուններ արտաբերել) բայի Futuro Simple-ը եզակի երրորդ դեմքի համար (él - նա)։',
    answer: 'cantará',
    explanation: 'Para la tercera persona del singular (él/ella/usted) en futuro simple, se añade la terminación "-á" acentuada al infinitivo del verbo regular: cantará.'
  },
  {
    id: 3,
    letter: 'D',
    prefixType: 'Con la',
    verb: 'decir (ասել)',
    tense: 'Futuro Perfecto',
    pronoun: 'nosotros',
    definition: 'Futuro perfecto de indicativo del verbo DECIR para la primera persona del plural (nosotros), considerando que tiene un participio irregular.',
    translation: 'DECIR (ասել - մտքերն արտահայտել խոսքի միջոցով) բայի Futuro Perfecto-ն հոգնակի առաջին դեմքի համար (nosotros - մենք)` հաշվի առնելով անկանոն դերբայը (dicho)։',
    answer: 'habremos dicho',
    explanation: 'Se forma utilizando el futuro de haber para nosotros ("habremos") junto al participio fuertemente irregular del verbo decir, que es "dicho" (no decido).'
  },
  {
    id: 4,
    letter: 'E',
    prefixType: 'Con la',
    verb: 'escribir (գրել)',
    tense: 'Futuro Simple',
    pronoun: 'ellos',
    definition: 'Futuro simple de indicativo del verbo ESCRIBIR para la tercera persona del plural (ellos).',
    translation: 'ESCRIBIR (գրել - տառեր կամ նշաններ պատկերել թղթի վրա) բայի Futuro Simple-ը հոգնակի երրորդ դեմքի համար (ellos - նրանք)։',
    answer: 'escribirán',
    explanation: 'En el futuro simple de indicativo, todos los infinitivos de las tres conjugaciones añaden el sufijo "-án" para la tercera persona del plural (ellos/ellas/ustedes): escribirán.'
  },
  {
    id: 5,
    letter: 'F',
    prefixType: 'Con la',
    verb: 'fabricar (արտադրել)',
    tense: 'Futuro Perfecto',
    pronoun: 'yo',
    definition: 'Futuro perfecto de indicativo del verbo FABRICAR para la primera persona del singular (yo).',
    translation: 'FABRICAR (արտադրել/պատրաստել - նյութական բարիքներ կամ իրեր ստեղծել) բայի Futuro Perfecto-ն եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'habré fabricado',
    explanation: 'El futuro perfecto se compone de la primera persona del singular del futuro del verbo haber ("habré") más el participio del verbo fabricar ("fabricado").'
  },
  {
    id: 6,
    letter: 'G',
    prefixType: 'Con la',
    verb: 'ganar (հաղթել)',
    tense: 'Futuro Simple',
    pronoun: 'nosotros',
    definition: 'Futuro simple de indicativo del verbo GANAR para la primera persona del plural (nosotros).',
    translation: 'GANAR (հաղթել/վաստակել - հաջողության հասնել մրցույթում կամ գումար ստանալ աշխատանքի դիմաց) բայի Futuro Simple-ը հոգնակի առաջին դեմքի համար (nosotros - մենք)։',
    answer: 'ganaremos',
    explanation: 'Para la primera persona del plural (nosotros), todos los verbos regulares e irregulares (salvo raras excepciones en su raíz) toman la desinencia "-emos" unida a su infinitivo: ganaremos.'
  },
  {
    id: 7,
    letter: 'H',
    prefixType: 'Con la',
    verb: 'hacer (անել)',
    tense: 'Futuro Simple',
    pronoun: 'tú',
    definition: 'Futuro simple de indicativo del verbo HACER para la segunda persona del singular (tú), con su correspondiente raíz irregular.',
    translation: 'HACER (անել/պատրաստել - գործողություն կատարել կամ որևէ բան ստեղծել) բայի Futuro Simple-ը եզակի երկրորդ դեմքի համար (tú - դու)՝ հաշվի առնելով անկանոն արմատը (har-)։',
    answer: 'harás',
    explanation: 'El verbo "hacer" tiene un futuro simple irregular donde se elimina la "c" y la "e" del infinitivo, quedando la raíz "har-", a la cual se le añade la terminación "-ás": harás.'
  },
  {
    id: 8,
    letter: 'I',
    prefixType: 'Con la',
    verb: 'ir (գնալ)',
    tense: 'Futuro Simple',
    pronoun: 'nosotros',
    definition: 'Futuro simple de indicativo del verbo IR para la primera persona del plural (nosotros).',
    translation: 'IR (գնալ - տեղաշարժվել մի վայրից մյուսը) բայի Futuro Simple-ը հոգնակի առաջին դեմքի համար (nosotros - մենք)։',
    answer: 'iremos',
    explanation: 'Aunque el verbo "ir" es altamente irregular en muchos tiempos verbales, en el futuro simple es completamente regular en su formación sobre el infinitivo: ir + emos = iremos.'
  },
  {
    id: 9,
    letter: 'J',
    prefixType: 'Con la',
    verb: 'jugar (խաղալ)',
    tense: 'Futuro Perfecto',
    pronoun: 'él',
    definition: 'Futuro perfecto de indicativo del verbo JUGAR para la tercera persona del singular (él/ella).',
    translation: 'JUGAR (խաղալ - զվարճանալ կամ կանոններով մրցել) բայի Futuro Perfecto-ն եզակի երրորդ դեմքի համար (él - նա)։',
    answer: 'habrá jugado',
    explanation: 'Compuesto del auxiliar haber en tercera persona ("habrá", con tilde) y el participio regular del verbo jugar ("jugado").'
  },
  {
    id: 10,
    letter: 'K',
    prefixType: 'Contiene la',
    verb: 'parkear (կայանել)',
    tense: 'Futuro Simple',
    pronoun: 'tú',
    definition: 'Futuro simple de indicativo del verbo coloquial PARKEAR (estacionar un vehículo), para la segunda persona del singular (tú).',
    translation: 'K տառը պարունակող PARKEAR (կայանել - ավտոմեքենան կայանել) բայի Futuro Simple-ը եզակի երկրորդ դեմքի համար (tú - դու)։',
    answer: 'parkearás',
    explanation: 'Al ser un verbo de conjugación regular, se añaden las terminaciones del futuro simple directamente sobre el infinitivo completo: parkear + ás = parkearás.'
  },
  {
    id: 11,
    letter: 'L',
    prefixType: 'Con la',
    verb: 'leer (կարդալ)',
    tense: 'Futuro Perfecto',
    pronoun: 'ellos',
    definition: 'Futuro perfecto de indicativo del verbo LEER para la tercera persona del plural (ellos). Recuerda la tilde del participio.',
    translation: 'LEER (կարդալ - գրավոր տեքստը ընկալել և հասկանալ) բայի Futuro Perfecto-ն հոգնակի երրորդ դեմքի համար (ellos - նրանք)՝ հաշվի առնելով դերբայի շեշտադրումը (leído)։',
    answer: 'habrán leído',
    explanation: 'El futuro del verbo auxiliar para ellos es "habrán" (con tilde) y el participio de leer es "leído" (la "i" lleva tilde para deshacer el diptongo formado con la anterior vocal).'
  },
  {
    id: 12,
    letter: 'M',
    prefixType: 'Con la',
    verb: 'morir (մահանալ)',
    tense: 'Futuro Perfecto',
    pronoun: 'él',
    definition: 'Futuro perfecto de indicativo de MORIR para la tercera persona del singular (él/ella), usando su participio irregular.',
    translation: 'MORIR (մահանալ - կորցնել կյանքը, դադարել գոյություն ունենալուց) բայի Futuro Perfecto-ն եզակի երրորդ դեմքի համար (él/ella - նա)՝ օգտագործելով անկանոն դերբայը (muerto)։',
    answer: 'habrá muerto',
    explanation: 'El verbo "morir" posee un participio irregular obligatorio que es "muerto". Unidos al auxiliar en tercera persona singular ("habrá"), se obtiene "habrá muerto".'
  },
  {
    id: 13,
    letter: 'N',
    prefixType: 'Con la',
    verb: 'nadar (լողալ)',
    tense: 'Futuro Simple',
    pronoun: 'vosotros',
    definition: 'Futuro simple de indicativo del verbo NADAR para la segunda persona del plural (vosotros).',
    translation: 'NADAR (լողալ - ջրի մեջ կամ վրա շարժվել մարմնի շարժումներով) բայի Futuro Simple-ը հոգնակի երկրորդ դեմքի համար (vosotros - դուք)։',
    answer: 'nadaréis',
    explanation: 'Se adiciona la terminación "-éis" con tilde obligatoria en la letra "e" al infinitivo completo regular "nadar": nadaréis.'
  },
  {
    id: 14,
    letter: 'Ñ',
    prefixType: 'Contiene la',
    verb: 'soñar (երզել)',
    tense: 'Futuro Simple',
    pronoun: 'yo',
    definition: 'Futuro simple de indicativo de un verbo con la letra Ñ: SOÑAR para la primera persona del singular (yo).',
    translation: 'Ñ տառը պարունակող SOÑAR (երազել/երազ տեսնել - քնած ժամանակ պատկերներ տեսնել կամ ինչ-որ բան ցանկանալ) բայի Futuro Simple-ը եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'soñaré',
    explanation: 'En el futuro simple no hay diptongación de la vocal de la raíz (como pasa en presente "sueño"). Mantiene el infinitivo completo más "-é": soñaré.'
  },
  {
    id: 15,
    letter: 'O',
    prefixType: 'Con la',
    verb: 'oír (լսել)',
    tense: 'Futuro Perfecto',
    pronoun: 'tú',
    definition: 'Futuro perfecto de indicativo del verbo OÍR para la segunda persona del singular (tú). Recuerda la tilde del participio.',
    translation: 'OÍR (լսել - ականջով ձայներ ընկալել) բայի Futuro Perfecto-ն եզակի երկրորդ դեմքի համար (tú - դու)՝ «oído» դերբայով։',
    answer: 'habrás oído',
    explanation: 'Formado con el auxiliar "habrás" y el participio "oído" (la "i" requiere tilde para marcar el hiato con la vocal o).'
  },
  {
    id: 16,
    letter: 'P',
    prefixType: 'Con la',
    verb: 'poder (կարողանալ)',
    tense: 'Futuro Simple',
    pronoun: 'él',
    definition: 'Futuro simple de indicativo de un verbo con raíz irregular PODER, conjugado para la tercera persona del singular (él/ella).',
    translation: 'PODER (կարողանալ - հնարավորություն կամ ուժ ունենալ որևէ բան անելու) բայի Futuro Simple-ը եզակի երրորդ դեմքի համար (él - նա)՝ անկանոն արմատով (podr-)։',
    answer: 'podrá',
    explanation: 'El verbo "poder" pierde la "e" del infinitivo en el futuro simple, usando la raíz irregular "podr-". Para la tercera persona impersonal o singular, se añade "-á": podrá.'
  },
  {
    id: 17,
    letter: 'Q',
    prefixType: 'Con la',
    verb: 'querer (ցանկանալ)',
    tense: 'Futuro Simple',
    pronoun: 'nosotros',
    definition: 'Futuro simple de indicativo del verbo QUERER para la primera persona del plural (nosotros), con la duplicación consonántica de su raíz.',
    translation: 'QUERER (ցանկանալ/սիրել - ձգտում ունենալ կամ սեր տածել) բայի Futuro Simple-ը հոգնակի առաջին դեմքի համար (nosotros - մենք)՝ երկակի "rr" արմատով (querr-)։',
    answer: 'querremos',
    explanation: 'El infinitivo "querer" pierde la "e" final convirtiéndose en la raíz con doble ere "querr-". Al añadir "-emos" para nosotros se conjuga como "querremos".'
  },
  {
    id: 18,
    letter: 'R',
    prefixType: 'Con la',
    verb: 'reír (ծիծաղել)',
    tense: 'Futuro Simple',
    pronoun: 'tú',
    definition: 'Futuro simple de indicativo del verbo REÍR para la segunda persona del singular (tú). Atento a los acentos gráficos.',
    translation: 'REÍR (ծիծաղել - ուրախություն արտահայտել ձայնով և դեմքի շարժումներով) բայի Futuro Simple-ը եզակի երկրորդ դեմքի համար (tú - դու)՝ reirás:',
    answer: 'reirás',
    explanation: 'En el futuro simple mantiene el infinitivo completo "reir" y agrega "-ás" con acento en la letra "a": reirás.'
  },
  {
    id: 19,
    letter: 'S',
    prefixType: 'Con la',
    verb: 'saber (իմանալ)',
    tense: 'Futuro Simple',
    pronoun: 'yo',
    definition: 'Futuro simple de indicativo del verbo irregular SABER para la primera persona del singular (yo) con cambio completo de raíz.',
    translation: 'SABER (իմանալ - տեղեկացված լինել կամ գիտելիք ունենալ) բայի Futuro Simple-ը եզակի առաջին դեմքի համար (yo - ես)՝ անկանոն արմատով (sabr-)։',
    answer: 'sabré',
    explanation: 'El verbo "saber" tiene la raíz irregular "sabr-" en futuro simple (pierde la vocal e del infinitivo). Para la primera persona singular agregamos "-é": sabré.'
  },
  {
    id: 20,
    letter: 'T',
    prefixType: 'Con la',
    verb: 'tener (ունենալ)',
    tense: 'Futuro Simple',
    pronoun: 'ellos',
    definition: 'Futuro simple de indicativo del verbo irregular TENER para la tercera persona del plural (ellos).',
    translation: 'TENER (ունենալ - սեփականություն կամ որևէ հատկանիշ կրել) բայի Futuro Simple-ը հոգնակի երրորդ դեմքի համար (ellos - նրանք)՝ անկանոն արմատով (tendr-)։',
    answer: 'tendrán',
    explanation: 'El infinitivo tener cambia en futuro simple a la raíz con "d" irregular "tendr-". Se conjuga agregando "-án" para ellos: tendrán.'
  },
  {
    id: 21,
    letter: 'U',
    prefixType: 'Con la',
    verb: 'unir (միացնել)',
    tense: 'Futuro Perfecto',
    pronoun: 'nosotros',
    definition: 'Futuro perfecto de indicativo del verbo UNIR para la primera persona del plural (nosotros).',
    translation: 'UNIR (միացնել - երկու կամ ավելի տարրեր իրար կապել) բայի Futuro Perfecto-ն հոգնակի առաջին դեմքի համար (nosotros - մենք)։',
    answer: 'habremos unido',
    explanation: 'Se compone del futuro simple de indicativo de haber para nosotros ("habremos") y el participio de unir ("unido").'
  },
  {
    id: 22,
    letter: 'V',
    prefixType: 'Con la',
    verb: 'venir (գալ)',
    tense: 'Futuro Simple',
    pronoun: 'tú',
    definition: 'Futuro simple de indicativo de VENIR para la segunda persona del singular (tú), con su raíz irregular que incluye consonante de apoyo.',
    translation: 'VENIR (գալ - մոտենալ կամ ժամանել խոսողի գտնվելու վայրը) բայի Futuro Simple-ը եզակի երկրորդ դեմքի համար (tú - դու)՝ անկանոն արմատով (vendr-)։',
    answer: 'vendrás',
    explanation: 'El futuro de "venir" utiliza la raíz irregular "vendr-" (que incorpora una "d"). Para la persona "tú" se añade "-ás" con acento escrito: vendrás.'
  },
  {
    id: 23,
    letter: 'W',
    prefixType: 'Con la',
    verb: 'whatsappear (նամակագրվել)',
    tense: 'Futuro Simple',
    pronoun: 'él',
    definition: 'Futuro simple de indicativo del verbo coloquial WHATSAPPEAR (enviar mensajes de WhatsApp) para la tercera persona del singular (él/ella).',
    translation: 'WHATSAPPEAR (նամակագրվել - WhatsApp-ով հաղորդագրություններ ուղարկել) բայի Futuro Simple-ը եզակի երրորդ դեմքի համար (él/ella - նա)։',
    answer: 'whatsappeará',
    explanation: 'Funciona como un verbo regular de la primera conjugación en futuro simple, añadiendo la terminación "-á" al infinitivo completo: whatsappeará.'
  },
  {
    id: 24,
    letter: 'X',
    prefixType: 'Contiene la',
    verb: 'explicar (բացատրել)',
    tense: 'Futuro Perfecto',
    pronoun: 'yo',
    definition: 'Futuro perfecto de indicativo del verbo que contiene la X: EXPLICAR para la primera persona del singular (yo).',
    translation: 'X տառը պարունակող EXPLICAR (բացատրել - ինչ-որ բան հասկանալի և պարզ դարձնել) բայի Futuro Perfecto-ն եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'habré explicado',
    explanation: 'Se forma con el futuro de haber en primera persona del singular ("habré") más el participio regular del verbo regular de la primera conjugación "explicado".'
  },
  {
    id: 25,
    letter: 'Y',
    prefixType: 'Contiene la',
    verb: 'construir (կառուցել)',
    tense: 'Futuro Simple',
    pronoun: 'él',
    definition: 'Futuro simple de indicativo de CONSTRUIR para la tercera persona del singular (él/ella).',
    translation: 'CONSTRUIR (կառուցել - շինություն կամ կառուցվածք ստեղծել մասերը հավաքելով) բայի Futuro Simple-ը եզակի երրորդ դեմքի համար (él/ella - նա)։',
    answer: 'construirá',
    explanation: 'Añade de forma regular la terminación "-á" sobre su infinitivo original para la tercera de singular: construir + á = construirá.'
  },
  {
    id: 26,
    letter: 'Z',
    prefixType: 'Contiene la',
    verb: 'empezar (սկսել)',
    tense: 'Futuro Simple',
    pronoun: 'nosotros',
    definition: 'Futuro simple de indicativo de EMPEZAR para la primera persona del plural (nosotros).',
    translation: 'EMPEZAR (սկսել - որևէ գործողության կամ երևույթի սկիզբը դնել) բայի Futuro Simple-ը հոգնակի առաջին դեմքի համար (nosotros - մենք)։',
    answer: 'empezaremos',
    explanation: 'En el futuro simple mantiene el infinitivo completo de la raíz con zeta intacta y se añade la desinencia "-emos": empezar + emos = empezaremos.'
  },
  {
    id: 27,
    letter: 'CH',
    prefixType: 'Con la',
    verb: 'chocar (բախվել)',
    tense: 'Futuro Simple',
    pronoun: 'tú',
    definition: 'Futuro simple de indicativo del verbo del dígrafo CH: CHOCAR para la segunda persona del singular (tú).',
    translation: 'CH երկգիրը պարունակող CHOCAR (բախվել - ուժգին հարվածել մի բանի կամ իրար) բայի Futuro Simple-ը եզակի երկրորդ դեմքի համար (tú - դու)։',
    answer: 'chocarás',
    explanation: 'La conjugación añade "-ás" sobre el infinitivo del verbo "chocar" de manera totalmente regular en este tiempo: chocarás.'
  },
  {
    id: 28,
    letter: 'LL',
    prefixType: 'Con la',
    verb: 'llegar (ժամանել)',
    tense: 'Futuro Perfecto',
    pronoun: 'él',
    definition: 'Futuro perfecto de indicativo del verbo con el dígrafo LL: LLEGAR para la tercera persona del singular (él/ella).',
    translation: 'LL երկգիրը պարունակող LLEGAR (ժամանել - հասնել նշանակված վայր կամ նպատակակետ) բայի Futuro Perfecto-ն եզակի երրորդ դեմքի համար (él - նա)։',
    answer: 'habrá llegado',
    explanation: 'Compuesto por "habrá" de tercera persona junto con el participio regular en "-ado" de llegar: habrá llegado.'
  },
  {
    id: 29,
    letter: '★',
    prefixType: 'Contiene la',
    verb: 'traer (բերել)',
    tense: 'Futuro Simple',
    pronoun: 'ellos',
    definition: 'Un reto final especial representable por la ESTRELLA (★): Futuro simple de indicativo de TRAER para la tercera persona del plural (ellos). Cuidado con la diptongación regular.',
    translation: '★ (աստղանիշ) հատուկ վերջնական մարտահրավեր՝ TRAER (բերել - իրը կամ անձին մոտեցնել խոսողին) բայի Futuro Simple-ը հոգնակի երրորդ դեմքի համար (ellos - նրանք)։',
    answer: 'traerán',
    explanation: 'El futuro simple del verbo "traer" se forma de forma estrictamente regular uniendo la desinencia "-án" a su infinitivo completo: traer + án = traerán.'
  }
];

export const QUESTIONS_P2: Question[] = [
  {
    id: 0,
    letter: 'A',
    prefixType: 'Con la',
    verb: 'andar (քայլել)',
    tense: 'Futuro Simple',
    pronoun: 'él',
    definition: 'Futuro simple de indicativo del verbo ANDAR para la tercera persona del singular (él/ella).',
    translation: 'ANDAR (քայլել/գնալ - ոտքով շարժվել առաջ կամ տեղաշարժվել) բայի Futuro Simple-ը եզակի երրորդ դեմքի համար (él/ella - նա)։',
    answer: 'andará',
    explanation: 'A diferencia de los pasados irregulares, andar se conjuga en futuro simple de indicativo de forma regular, agregando la terminación correspondiente al infinitivo: andará.'
  },
  {
    id: 1,
    letter: 'B',
    prefixType: 'Con la',
    verb: 'beber (խմել)',
    tense: 'Futuro Simple',
    pronoun: 'nosotros',
    definition: 'Futuro simple de indicativo del verbo BEBER para la primera persona del plural (nosotros).',
    translation: 'BEBER (խմել - հեղուկ կլանել, ծարավը հագեցնել) բայի Futuro Simple-ը հոգնակի առաջին դեմքի համար (nosotros - մենք)։',
    answer: 'beberemos',
    explanation: 'Se toma el infinitivo completo de la segunda conjugación "beber" y se le añade el sufijo "-emos" correspondiente a nosotros: beberemos.'
  },
  {
    id: 2,
    letter: 'C',
    prefixType: 'Con la',
    verb: 'caminar (քայլել)',
    tense: 'Futuro Perfecto',
    pronoun: 'yo',
    definition: 'Futuro perfecto de indicativo del verbo de la primera conjugación CAMINAR para la primera persona del singular (yo).',
    translation: 'CAMINAR (քայլել - քայլերով առաջանալ հաճույքի կամ տեղաշարժվելու համար) բայի Futuro Perfecto-ն եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'habré caminado',
    explanation: 'Se forma con el futuro de haber para la primera persona ("habré") más el participio regular terminado en "ado" de caminar.'
  },
  {
    id: 3,
    letter: 'D',
    prefixType: 'Con la',
    verb: 'dormir (քնել)',
    tense: 'Futuro Simple',
    pronoun: 'ellos',
    definition: 'Futuro simple de indicativo del verbo DORMIR para la tercera persona del plural (ellos).',
    translation: 'DORMIR (քնել - հանգստի վիճակում գտնվել, երբ գիտակցությունը ժամանակավորապես անջատված է) բայի Futuro Simple-ը հոգնակի երրորդ դեմքի համար (ellos - նրանք)։',
    answer: 'dormirán',
    explanation: 'En futuro simple no diptonga la vocal raíz (a diferencia del presente "duermen"). Se conserva el infinitivo completo más "-án": dormirán.'
  },
  {
    id: 4,
    letter: 'E',
    prefixType: 'Con la',
    verb: 'entender (հասկանալ)',
    tense: 'Futuro Perfecto',
    pronoun: 'tú',
    definition: 'Futuro perfecto de indicativo del verbo ENTENDER para la segunda persona del singular (tú).',
    translation: 'ENTENDER (հասկանալ - ըմբռնել երևույթի կամ խոսքի իմաստը) բայի Futuro Perfecto-ն եզակի երկրորդ դեմքի համար (tú - դու)։',
    answer: 'habrás entendido',
    explanation: 'Construido a partir del auxiliar haber para tú ("habrás") más el participio regular del verbo de la segunda conjugación "entendido".'
  },
  {
    id: 5,
    letter: 'F',
    prefixType: 'Con la',
    verb: 'felicitar (շնորհավորել)',
    tense: 'Futuro Simple',
    pronoun: 'él',
    definition: 'Futuro simple de indicativo del verbo FELICITAR para la tercera persona del singular (él/ella).',
    translation: 'FELICITAR (շնորհավորել - բարեմաղթանքներ հայտնել հաճելի առիթով) բայի Futuro Simple-ը եզակի երրորդ դեմքի համար (él/ella - նա)։',
    answer: 'felicitará',
    explanation: 'Se obtiene agregando la desinencia "-á" con acento escrito sobre el infinitivo de la primera conjugación: felicitar + á = felicitará.'
  },
  {
    id: 6,
    letter: 'G',
    prefixType: 'Con la',
    verb: 'gritar (բղավել)',
    tense: 'Futuro Simple',
    pronoun: 'nosotros',
    definition: 'Futuro simple de indicativo del verbo GRITAR para la primera persona del plural (nosotros).',
    translation: 'GRITAR (բղավել - բարձր ձայնով խոսել կամ կանչել) բայի Futuro Simple-ը հոգնակի առաջին դեմքի համար (nosotros - մենք)։',
    answer: 'gritaremos',
    explanation: 'Se adiciona el sufijo "-emos" sobre el infinitivo estándar regular "gritar" para obtener "gritaremos".'
  },
  {
    id: 7,
    letter: 'H',
    prefixType: 'Con la',
    verb: 'hablar (խոսել)',
    tense: 'Futuro Perfecto',
    pronoun: 'tú',
    definition: 'Futuro perfecto de indicativo del verbo HABLAR para la segunda persona del singular (tú).',
    translation: 'HABLAR (խոսել - լեզվի միջոցով մտքեր հայտնել կամ զրուցել) բայի Futuro Perfecto-ն եզակի երկրորդ դեմքի համար (tú - դու)։',
    answer: 'habrás hablado',
    explanation: 'Se compone de "habrás", futuro de haber, y el participio regular "hablado" de la primera conjugación.'
  },
  {
    id: 8,
    letter: 'I',
    prefixType: 'Con la',
    verb: 'intentar (փորձել)',
    tense: 'Futuro Simple',
    pronoun: 'yo',
    definition: 'Futuro simple de indicativo del verbo INTENTAR para la primera persona del singular (yo).',
    translation: 'INTENTAR (փորձել - ջանք թափել որևէ նպատակի հասնելու համար) բայի Futuro Simple-ը եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'intentaré',
    explanation: 'Como es un verbo de la primera conjugación, se añade directamente la terminación "-é" al infinitivo: yo intentaré.'
  },
  {
    id: 9,
    letter: 'J',
    prefixType: 'Con la',
    verb: 'juntarse (հավաքվել/միավորվել)',
    tense: 'Futuro Perfecto',
    pronoun: 'nosotros',
    definition: 'Futuro perfecto de indicativo del verbo reflexivo JUNTARSE para la primera persona del plural (nosotros). Recuerda colocar el pronombre de forma correcta.',
    translation: 'JUNTARSE (հավաքվել/միավորվել - մարդկանց կամ իրերի մեկտեղում) անդրադարձ բայի Futuro Perfecto-ն հոգնակի առաջին դեմքի համար (nosotros - մենք)՝ «nos» անդրադարձ դերանունով։',
    answer: 'nos habremos juntado',
    explanation: 'El pronombre reflexivo "nos" precede al verbo auxiliar en futuro perfecto ("habremos"), seguido por el participio regular "juntado".'
  },
  {
    id: 10,
    letter: 'K',
    prefixType: 'Con la',
    verb: 'kilometrar (չափել կիլոմետրեր)',
    tense: 'Futuro Simple',
    pronoun: 'yo',
    definition: 'Futuro simple de indicativo del verbo KILOMETRAR (recorrer kilómetros) para la primera persona del singular (yo).',
    translation: 'KILOMETRAR (չափել կիլոմետրով - մեքենայով կամ ոտքով անցած տարածությունը հաշվառել) բայի Futuro Simple-ը եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'kilometraré',
    explanation: 'Se adhiere el sufijo "-é" con tilde gramatical directamente sobre el infinitivo del verbo propuesto: kilometraré.'
  },
  {
    id: 11,
    letter: 'L',
    prefixType: 'Con la',
    verb: 'lavar (լվանալ)',
    tense: 'Futuro Simple',
    pronoun: 'ellos',
    definition: 'Futuro simple de indicativo del verbo LAVAR para la tercera persona del plural (ellos).',
    translation: 'LAVAR (լվանալ - ջրով կամ օճառով որևէ բան մաքրել) բայի Futuro Simple-ը հոգնակի երրորդ դեմքի համար (ellos - նրանք)։',
    answer: 'lavarán',
    explanation: 'Se toma el infinitivo completo de primera conjugación y se le añade el sufijo plural "-án" con tilde en la vocal: lavarán.'
  },
  {
    id: 12,
    letter: 'M',
    prefixType: 'Con la',
    verb: 'mirar (նայել)',
    tense: 'Futuro Perfecto',
    pronoun: 'él',
    definition: 'Futuro perfecto de indicativo del verbo MIRAR para la tercera persona del singular (él/ella).',
    translation: 'MIRAR (նայել - աչքերը ուղղել որևէ առարկայի կամ անձի վրա) բայի Futuro Perfecto-ն եզակի երրորդ դեմքի համար (él - նա)։',
    answer: 'habrá mirado',
    explanation: 'Se compone del futuro del verbo haber para la tercera persona ("habrá", que lleva acento ortográfico) acompañado del participio regular "mirado".'
  },
  {
    id: 13,
    letter: 'N',
    prefixType: 'Con la',
    verb: 'nadar (լողալ)',
    tense: 'Futuro Simple',
    pronoun: 'tú',
    definition: 'Futuro simple de indicativo del verbo regular NADAR para la segunda persona del singular (tú).',
    translation: 'NADAR (լողալ - ջրի մեջ կամ վրա շարժվել մարմնի շարժումներով) բայի Futuro Simple-ը եզակի երկրորդ դեմքի համար (tú - դու)։',
    answer: 'nadarás',
    explanation: 'Se le añade la terminación "-ás" acentuada sobre el infinitivo "nadar" obteniendo el futuro predictivo del singular: nadarás.'
  },
  {
    id: 14,
    letter: 'Ñ',
    prefixType: 'Contiene la',
    verb: 'teñir (ներկել)',
    tense: 'Futuro Simple',
    pronoun: 'él',
    definition: 'Futuro simple de indicativo del verbo TEÑIR (contiene la Ñ) para la tercera persona del singular (él/ella).',
    translation: 'Ñ տառ պարունակող TEÑIR (ներկել - մազերին կամ գործվածքին գույն տալ) բայի Futuro Simple-ը եզակի երրորդ դեմքի համար (él - նա)։',
    answer: 'teñirá',
    explanation: 'Los verbos de tercera conjugación regulares en futuro expresan predicciones añadiendo la desinencia "-á" a su infinitivo original: teñirá.'
  },
  {
    id: 15,
    letter: 'O',
    prefixType: 'Con la',
    verb: 'olvidar (մոռանալ)',
    tense: 'Futuro Perfecto',
    pronoun: 'nosotros',
    definition: 'Futuro perfecto de indicativo de OLVIDAR para la primera persona del plural (nosotros).',
    translation: 'OLVIDAR (մոռանալ - հիշողությունից կորցնել տեղեկությունը կամ իրը չվերցնել) բայի Futuro Perfecto-ն հոգնակի առաջին դեմքի համար (nosotros - մենք)։',
    answer: 'habremos olvidado',
    explanation: 'Combina el verbo auxiliar haber en su forma futura plural ("habremos") y el participio regular de olvidar ("olvidado").'
  },
  {
    id: 16,
    letter: 'P',
    prefixType: 'Con la',
    verb: 'pensar (մտածել)',
    tense: 'Futuro Simple',
    pronoun: 'tú',
    definition: 'Futuro simple de indicativo del verbo PENSAR para la segunda persona del singular (tú).',
    translation: 'PENSAR (մտածել - մտավոր գործունեություն ծավալել, վերլուծել) բայի Futuro Simple-ը եզակի երկրորդ դեմքի համար (tú - դու)։',
    answer: 'pensarás',
    explanation: 'No varía su raíz en este tiempo a diferencia del presente "piensas". Mantiene el infinitivo regular uniendo el sufijo "-ás": pensarás.'
  },
  {
    id: 17,
    letter: 'Q',
    prefixType: 'Con la',
    verb: 'quemar (այրել)',
    tense: 'Futuro Perfecto',
    pronoun: 'yo',
    definition: 'Futuro perfecto de indicativo de QUEMAR para la primera persona del singular (yo).',
    translation: 'QUEMAR (այրել - կրակով կամ տաքությամբ ոչնչացնել կամ վնասել) բայի Futuro Perfecto-ն եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'habré quemado',
    explanation: 'Utiliza el auxiliar "habré" de indicativo con tilde en la vocal posterior junto al participio estandarizado "quemado".'
  },
  {
    id: 18,
    letter: 'R',
    prefixType: 'Con la',
    verb: 'romper (կոտրել)',
    tense: 'Futuro Simple',
    pronoun: 'él',
    definition: 'Futuro simple de indicativo del verbo ROMPER para la tercera persona del singular (él/ella).',
    translation: 'ROMPER (կոտրել- առարկան մասերի բաժանել հարվածով կամ պատռելով) բայի Futuro Simple-ը եզակի երրորդ դեմքի համար (él/ella - նա)։',
    answer: 'romperá',
    explanation: 'Formado agregándole regularmente "-á" con tilde sobre su infinitivo regular: romper + á = romperá.'
  },
  {
    id: 19,
    letter: 'S',
    prefixType: 'Con la',
    verb: 'sentir (զգալ)',
    tense: 'Futuro Simple',
    pronoun: 'ellos',
    definition: 'Futuro simple de indicativo de SENTIR para la tercera persona del plural (ellos).',
    translation: 'SENTIR (զգալ - ֆիզիկական կամ հուզական ընկալում ունենալ) բայի Futuro Simple-ը հոգնակի երրորդ դեմքի համար (ellos - նրանք)։',
    answer: 'sentirán',
    explanation: 'Para la tercera persona del plural, se añade la terminación "-án" sobre el infinitivo del verbo regular de la tercera conjugación: sentir + án = sentirán.'
  },
  {
    id: 20,
    letter: 'T',
    prefixType: 'Con la',
    verb: 'trabajar (աշխատել)',
    tense: 'Futuro Simple',
    pronoun: 'nosotros',
    definition: 'Futuro simple de indicativo del verbo TRABAJAR para la primera persona del plural (nosotros).',
    translation: 'TRABAJAR (աշխատել - ֆիզիկական կամ մտավոր գործունեություն ծավալել) բայի Futuro Simple-ը հոգնակի առաջին դեմքի համար (nosotros - մենք)։',
    answer: 'trabajaremos',
    explanation: 'Verbo de primera conjugación altamente regular, añade el sufijo "-emos" sobre el infinitivo natural: trabajaremos.'
  },
  {
    id: 21,
    letter: 'U',
    prefixType: 'Con la',
    verb: 'usar (օգտագործել)',
    tense: 'Futuro Perfecto',
    pronoun: 'él',
    definition: 'Futuro perfecto de indicativo del verbo USAR para la tercera persona del singular (él/ella).',
    translation: 'USAR (օգտագործել - որևէ բան կիրառել որպես գործիք կամ միջոց) բայի Futuro Perfecto-ն եզակի երրորդ դեմքի համար (él - նա)։',
    answer: 'habrá usado',
    explanation: 'Compuesto por "habrá" de la tercera persona singular, unida al participio regular del verbo propuesto "usado".'
  },
  {
    id: 22,
    letter: 'V',
    prefixType: 'Con la',
    verb: 'vivir (ապրել)',
    tense: 'Futuro Perfecto',
    pronoun: 'tú',
    definition: 'Futuro perfecto de indicativo del de la tercera conjugación VIVIR para la segunda persona del singular (tú).',
    translation: 'VIVIR (ապրել - կենսաբանական գոյություն կրել կամ որևէ վայրում բնակվել) բայի Futuro Perfecto-ն եզակի երկրորդ դեմքի համար (tú - դու)։',
    answer: 'habrás vivido',
    explanation: 'Combina el verbo haber en tiempo de futuro simple de segunda persona ("habrás") unido junto al participio regular "vivido".'
  },
  {
    id: 23,
    letter: 'W',
    prefixType: 'Con la',
    verb: 'windsurfear (վինդսերֆինգ անել)',
    tense: 'Futuro Simple',
    pronoun: 'yo',
    definition: 'Futuro simple de indicativo del neologismo WINDSURFEAR para la primera persona del singular (yo).',
    translation: 'WINDSURFEAR (վինդսերֆինգ անել - առագաստով տախտակի վրա սահել ջրի վրա) բայի Futuro Simple-ը եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'windsurfearé',
    explanation: 'Mantiene las terminaciones regulares uniendo "-é" sobre su infinitivo compuesto neológico: windsurfearé.'
  },
  {
    id: 24,
    letter: 'X',
    prefixType: 'Contiene la',
    verb: 'exigir (պահանջել)',
    tense: 'Futuro Simple',
    pronoun: 'ellos',
    definition: 'Futuro simple de indicativo de un verbo que contiene la X: EXIGIR para la tercera persona del plural (ellos).',
    translation: 'X տառը պարունակող EXIGIR (պահանջել - իրավունքով կամ կտրուկ կերպով որևէ բան ուզել) բայի Futuro Simple-ը հոգնակի երրորդ դեմքի համար (ellos - նրանք)։',
    answer: 'exigirán',
    explanation: 'Todos los verbos en "-ir" forman el futuro simple sumando "-án" (con tilde) a su infinitivo original: exigirán.'
  },
  {
    id: 25,
    letter: 'Y',
    prefixType: 'Contiene la',
    verb: 'huir (փախչել)',
    tense: 'Futuro Simple',
    pronoun: 'ellos',
    definition: 'Futuro simple de indicativo del verbo irregular HUIR para la tercera persona del plural (ellos).',
    translation: 'Y տառ պարունակող HUIR (փախչել - վտանգից կամ անախորժությունից հեռանալ արագորեն) բայի Futuro Simple-ը հոգնակի երրորդ դեմքի համար (ellos - նրանք)։',
    answer: 'huirán',
    explanation: 'Incluso siendo irregular, mantiene el infinitivo "huir" como base y agrega la desinencia acentuada estándar "-án": huirán.'
  },
  {
    id: 26,
    letter: 'Z',
    prefixType: 'Contiene la',
    verb: 'cruzar (անցնել)',
    tense: 'Futuro Simple',
    pronoun: 'yo',
    definition: 'Futuro simple de indicativo del verbo CRUZAR (contiene la Z) para la primera persona del singular (yo).',
    translation: 'Z տառ պարունակող CRUZAR (անցնել - ճանապարհը կամ սահմանը հատել) բայի Futuro Simple-ը եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'cruzaré',
    explanation: 'No cambia sorda ortográfica "z" por "c" en este tiempo debido a que no precede vocal problemática. Queda simplemente: cruzaré.'
  },
  {
    id: 27,
    letter: 'CH',
    prefixType: 'Con la',
    verb: 'charlar (զրուցել)',
    tense: 'Futuro Perfecto',
    pronoun: 'yo',
    definition: 'Futuro perfecto de indicativo de CHARLAR para la primera persona del singular (yo).',
    translation: 'CHARLAR (զրուցել - թեթևակի խոսակցություն ունենալ ընկերական մթնոլորտում) բայի Futuro Perfecto-ն եզակի առաջին դեմքի համար (yo - ես)։',
    answer: 'habré charlado',
    explanation: 'Formado con el futuro del verbo haber para la primera de singular "habré" más el participio regular "charlado".'
  },
  {
    id: 28,
    letter: 'LL',
    prefixType: 'Con la',
    verb: 'llamar (զանգահարել)',
    tense: 'Futuro Simple',
    pronoun: 'tú',
    definition: 'Futuro simple de indicativo de LLAMAR para la segunda persona del singular (tú).',
    translation: 'LLAMAR (զանգահարել/կանչել - ձայն տալ կամ հեռախոսով կապվել) բայի Futuro Simple-ը եզակի երկրորդ դեմքի համար (tú - դու)։',
    answer: 'llamarás',
    explanation: 'Se deriva sumándole de forma estándar "-ás" con tilde sobre su infinitivo regular: llamar + ás = llamarás.'
  },
  {
    id: 29,
    letter: '★',
    prefixType: 'Contiene la',
    verb: 'conducir (վարել)',
    tense: 'Futuro Simple',
    pronoun: 'ellos',
    definition: 'Un reto final especial con estrella (★): Futuro simple de indicativo del verbo irregular CONDUCIR para la tercera persona del plural (ellos).',
    translation: '★ (աստղանիշ) հատուկ վերջնական մարտահրավեր՝ CONDUCIR (վարել/առաջնորդել - տրանսպորտային միջոց կառավարել) բայի Futuro Simple-ը հոգնակի երրորդ դեմքի համար (ellos - նրանք)։',
    answer: 'conducirán',
    explanation: 'El futuro simple mantiene el infinitivo completo de conducir de forma regular agregando la desinencia estándar "-án": conducirán.'
  }
];
